formatter: "markdown table" # this is required

version: ""

header-from: main.tf
footer-from: ""

sections:
  hide: []
  show: []

content: |-
 
  {{ .Header }}
  
  ## Code Dependencies Graph
  <center>

     ![Graph](./graph.svg)

    ##### **Dependency Graph**
  
  </center>
  
  ---
  
  ## Example parameter options for each environment
  
  ```hcl
  {{ include "./parameters.tf" }}
  ```

  {{ .Providers }}

  {{ .Outputs }}

  {{ .Inputs }}
  
output:
  file: "README.md"
  mode: replace
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  required: true
  sensitive: true
  type: true
  show: requirements